"""add goal, category, saved_vacancy

Revision ID: 1605d7ed3d36
Revises: 
Create Date: 2026-03-20 15:30:40.042436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1605d7ed3d36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_items', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.add_column('roadmap_items', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'roadmap_items', 'goals', ['goal_id'], ['id'])
    op.add_column('sessions', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sessions', 'goals', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'goal_id')
    op.drop_constraint(None, 'roadmap_items', type_='foreignkey')
    op.drop_column('roadmap_items', 'category')
    op.drop_column('roadmap_items', 'goal_id')
    # ### end Alembic commands ###
